project:
  type: website
  output-dir: docs

website:
  title: "RNAseq-workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Exercises
        menu:
          - src/exercises/exercise1_R_basics.qmd
          - src/exercises/exercise2_data_loading.qmd
          - src/exercises/exercise3_qc.qmd
          - src/exercises/exercise4_de.qmd
          - src/exercises/exercise5_enrichment.qmd
      - text: Single Cell Exercises
        menu:
          - src/exercises/exercise_sc1_data_loading.qmd
          - src/exercises/exercise_sc2_preprocessing.qmd
          - src/exercises/exercise_sc3_clustering.qmd
          - src/exercises/exercise_sc4_de.qmd
      - text: Presentations
        menu:
          - href: src/presentations/RNAseq_basics.html
            text: "RNAseq Basics"
          - href: src/presentations/R_basics.html
            text: "R Basics"
          - href: src/presentations/Functional_analysis.html
            text: "Functional Analysis"
          - href: src/presentations/Enrichment_analysis.html
            text: "Enrichment Analysis"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



